export const actions = {
    profile:{
        DATA_FETCHING: 'PROFILE_DATA_FETCHING',
        DATA_FETCHID: 'PROFILE_DATA_FETCHID',
        DATA_FETCHID_ERROR: 'PROFILE_DATA_FETCHID_ERROR',
        USER_DATA_EDIT: 'PROFILE_USER_DATA_EDIT',
        IMAGE_UPDATED: 'PROFILE_IMAGE_UPDATED',
    }
}